wandb_ssh_key: "KEY"

wandb_init:
  project: "experiment1"
  name: "experiment"
  entity: "emiliia_antonii_dl_project"


type: "all"
# single -- single experiment
# simultanious -- iterate over hyperparameters simultaniously
# all -- consider all combinations of the hyperparameters

use_gpu: True
# if False then cpu is used
