meta:
  wandb_ssh_key: "38b41b4540f5f67c13a4d36ca7c2eda9cd91eb83"

  wandb_init:
    project: "test_run"
    entity: "emiliia_antonii_dl_project"

  type: "simultanious"
  # single -- single experiment
  # simultanious -- iterate over hyperparameters simultaniously
  # all -- consider all combinations of the hyperparameters

  use_gpu: True
  # if False then cpu is used
