meta:
  wandb_ssh_key: "7694788bdc5e6da87482e00cfb4349f137fdd5ad"

  wandb_init:
    project: "test_run_simultanious"
    entity: "emiliia_antonii_dl_project"

  type: "single"
  # single -- single experiment
  # simultanious -- iterate over hyperparameters simultaniously
  # all -- consider all combinations of the hyperparameters

  use_gpu: True
  # if False then cpu is used
