meta:
  wandb_ssh_key: "22952912b9ae47907d106100821cb4c75d982255"

  wandb_init:
    project: "experiment1"
    entity: "emiliia_antonii_dl_project"

  type: "all"
  # single -- single experiment
  # simultanious -- iterate over hyperparameters simultaniously
  # all -- consider all combinations of the hyperparameters

  use_gpu: True
  # if False then cpu is used
